title: Becoming
description: Notes on inner evolution.
url: https://myaccount.github.io
baseurl: /name-of-blog-repo
permalink: /:slug/
markdown: kramdown
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
# Ensure Liquid date format works the same locally/GitHub
timezone: Europe/Berlin
